### ISSUE TITLE
Incorrect Reading of 8-bit Signed Char Attributes

### ISSUE THREAD

**Issue by a-shahba** [PDLPorters/pdl-io-hdf5#5]
I was trying to read an array-valued attribute from an HDF file using `PDL::IO::HDF5` package and noticed that the return value is incorrect. The attribute datatype is 8-bit signed char (`H5T_STD_I8LE`) and I expected the package to return `[-127, 127]`, but instead it returned `[129, 127]`. Examining the source code, I found out why this is happening. 

The code maps `H5T_STD_I8LE` to `$PDL::Types::PDL_B` [here](https://github.com/PDLPorters/pdl-io-hdf5/blob/master/HDF5/Dataset.pm#L432). However, `$PDL::Types::PDL_B` represents an unsigned char datatype. Therefore, the bits representing `-127` in the buffer are interpreted as `129` by PDL.

To correct this behavior, I suggest that `H5T_STD_I8LE` and `H5T_STD_I8BE` are mapped to  `$PDL::Types::PDL_SB` which represents signed char datatype.

**Comment by mohawk2** [comment]
I agree! Feel like making a pull request implementing that? You'll need to add a test case similar to what triggered this.

**Comment by a-shahba** [comment]
Thanks, @mohawk2. Sure, I will work on it and submit a PR.

**Comment by mohawk2** [comment]
This is fixed and released as 0.76.

**Comment by a-shahba** [comment]
Thanks. You are very fast. I was going to work on it this weekend.
